import { dirname, relative } from 'node:path';

import type { ContentMode, LoadedAgent, LoadedInstruction, RenderedFile } from './model.js';
import { providerSkillName } from './load.js';

const GENERATED_MARKER = '<!-- GENERATED by nevo-repo-agents. DO NOT EDIT. -->';

function yamlString(value: string): string {
  return JSON.stringify(value);
}

function appliesWhen(instruction: LoadedInstruction): string | null {
  return instruction.applies === 'always' ? null : instruction.applies.when;
}

function effectiveDelivery(
  instruction: LoadedInstruction,
  mode: ContentMode,
): 'inline' | 'reference' {
  if (instruction.delivery === 'inline' || instruction.delivery === 'reference')
    return instruction.delivery;
  return mode === 'embed' ? 'inline' : 'reference';
}

function linkFrom(skillPath: string, sourcePath: string, repoRoot: string): string {
  const target = relative(dirname(skillPath), sourcePath).replaceAll('\\', '/');
  const repositoryPath = relative(repoRoot, sourcePath).replaceAll('\\', '/');
  return `[\`${repositoryPath}\`](${target.startsWith('.') ? target : `./${target}`})`;
}

function renderInline(instruction: LoadedInstruction): string {
  const when = appliesWhen(instruction);
  return [
    `## ${instruction.title}`,
    ...(when
      ? [
          '',
          `**Applies when:** ${when}.`,
          `**Requirement:** ${instruction.required ? 'Required when applicable.' : 'Optional.'}`,
        ]
      : []),
    '',
    instruction.content,
  ].join('\n');
}

function renderReferenceTable(
  title: string,
  instructions: readonly LoadedInstruction[],
  skillPath: string,
  repoRoot: string,
  conditional: boolean,
): string {
  if (instructions.length === 0) return '';
  const lines = [`## ${title}`, ''];
  if (conditional) {
    lines.push('| What | When | Description | Source |', '|---|---|---|---|');
    for (const instruction of instructions) {
      const label = instruction.required
        ? `${instruction.title} (required when applicable)`
        : instruction.title;
      lines.push(
        `| ${label} | ${appliesWhen(instruction) ?? 'always'} | ${instruction.description ?? ''} | ${linkFrom(skillPath, instruction.absoluteSource, repoRoot)} |`,
      );
    }
  } else {
    lines.push('| What | Description | Source |', '|---|---|---|');
    for (const instruction of instructions) {
      const label = instruction.required ? `${instruction.title} (required)` : instruction.title;
      lines.push(
        `| ${label} | ${instruction.description ?? ''} | ${linkFrom(skillPath, instruction.absoluteSource, repoRoot)} |`,
      );
    }
  }
  lines.push('');
  return lines.join('\n');
}

function renderRequiredKnowledge(agent: LoadedAgent): string {
  if (agent.knowledge.required.length === 0) return '';
  return [
    '## Required repository knowledge',
    '',
    'Before starting work, load these exact stable document IDs. They are profile requirements and must not be replaced by lexical discovery:',
    '',
    '```bash',
    `pnpm docs:get ${agent.knowledge.required.join(' ')}`,
    '```',
  ].join('\n');
}

function allowsAutomaticSelection(agent: LoadedAgent): boolean {
  return agent.selection.modes.includes('automatic');
}

function projectedDescription(agent: LoadedAgent): string {
  if (!allowsAutomaticSelection(agent)) {
    return `Use only when the ${agent.id} profile is explicitly selected by the user, workflow, or orchestrator. ${agent.description}`;
  }
  return agent.description;
}

function renderSelection(agent: LoadedAgent): string {
  if (!allowsAutomaticSelection(agent)) {
    return [
      '**Selection:** explicit only.',
      'Use this profile only when the user, workflow, or orchestrator explicitly selects it.',
    ].join(' ');
  }

  return [
    '**Selection:** explicit or automatic.',
    'Automatic selection is allowed when the current invocation or execution policy permits it.',
    'Selection happens before the profile becomes active; once active, do not switch profiles merely because later task wording resembles another profile.',
  ].join(' ');
}

export function renderSkill(
  repoRoot: string,
  agent: LoadedAgent,
  outputPath: string,
  mode: ContentMode,
): RenderedFile {
  const inline: LoadedInstruction[] = [];
  const alwaysRefs: LoadedInstruction[] = [];
  const conditionalRefs: LoadedInstruction[] = [];

  for (const instruction of agent.instructions) {
    const delivery = effectiveDelivery(instruction, mode);
    if (delivery === 'inline') inline.push(instruction);
    else if (instruction.applies === 'always') alwaysRefs.push(instruction);
    else conditionalRefs.push(instruction);
  }

  const frontmatter = [
    '---',
    `name: ${providerSkillName(agent.id)}`,
    `description: ${yamlString(projectedDescription(agent))}`,
    '---',
  ].join('\n');
  const sections = [
    frontmatter,
    GENERATED_MARKER,
    `# ${agent.name}\n\nCanonical profile: \`${agent.id}\`.\n\n${renderSelection(agent)}`,
    renderRequiredKnowledge(agent),
    ...inline.map(renderInline),
    renderReferenceTable('Read also', alwaysRefs, outputPath, repoRoot, false),
    renderReferenceTable('Conditional instructions', conditionalRefs, outputPath, repoRoot, true),
  ].filter((part) => part.trim().length > 0);
  const body = `${sections
    .join('\n\n')
    .replace(/\n{3,}/g, '\n\n')
    .trimEnd()}\n`;

  return { path: outputPath, content: body };
}

export { GENERATED_MARKER };
