import type { CSSProperties } from 'react';

import { hexFromRgb, mixRgb, normalizeHex, rgbFromHex, rgba } from './color';

export const DEFAULT_BRAND_PRIMARY = '#2b6bff';
export const appBackgroundClassName = 'bg-canvas bg-app-base';
export const workspaceSurfaceClassName =
  'workspace-surface-material relative bg-workspace-material bg-workspace';

export interface BrandEnvironment {
  primary: string;
  actionHover: string;
  focusRing: string;
  actionGlow: string;
  ambientSubtle: string;
  ambientMedium: string;
  ambientDeep: string;
  appBackgroundImage: string;
  workspaceBackgroundImage: string;
}

export type BrandEnvironmentStyle = CSSProperties & {
  '--color-brand-primary': string;
  '--color-action-primary-hover': string;
  '--color-focus-ring': string;
  '--drop-shadow-action-glow': string;
  '--background-image-app-base': string;
  '--background-image-workspace': string;
};

export function deriveBrandEnvironment(primary = DEFAULT_BRAND_PRIMARY): BrandEnvironment {
  const normalizedPrimary = normalizeHex(primary);
  const source = rgbFromHex(normalizedPrimary);
  const black = { r: 0, g: 0, b: 0 };
  const white = { r: 255, g: 255, b: 255 };
  const medium = mixRgb(source, black, 0.14);
  const deep = mixRgb(source, black, 0.34);
  const ambientSubtle = rgba(source, 0.026);
  const ambientMedium = rgba(medium, 0.082);
  const ambientDeep = rgba(deep, 0.04);

  return {
    primary: normalizedPrimary,
    actionHover: hexFromRgb(mixRgb(source, black, 0.16)),
    focusRing: hexFromRgb(mixRgb(source, white, 0.34)),
    actionGlow: rgba(source, 0.38),
    ambientSubtle,
    ambientMedium,
    ambientDeep,
    appBackgroundImage: [
      `radial-gradient(ellipse 64% 48% at 12% 0%, ${ambientMedium} 0%, ${ambientSubtle} 44%, transparent 74%)`,
      `radial-gradient(ellipse 44% 34% at 100% 100%, ${ambientDeep} 0%, transparent 72%)`,
    ].join(', '),
    workspaceBackgroundImage:
      'radial-gradient(ellipse 34% 24% at 0% 0%, rgba(255, 255, 255, 0.055) 0%, rgba(255, 255, 255, 0.016) 42%, transparent 72%)',
  };
}

export function brandEnvironmentStyle(primary = DEFAULT_BRAND_PRIMARY): BrandEnvironmentStyle {
  const environment = deriveBrandEnvironment(primary);
  return {
    '--color-brand-primary': environment.primary,
    '--color-action-primary-hover': environment.actionHover,
    '--color-focus-ring': environment.focusRing,
    '--drop-shadow-action-glow': `0 0 5px ${environment.actionGlow}`,
    '--background-image-app-base': environment.appBackgroundImage,
    '--background-image-workspace': environment.workspaceBackgroundImage,
  };
}

export function renderBrandEnvironmentCss(primary = DEFAULT_BRAND_PRIMARY): string {
  const environment = deriveBrandEnvironment(primary);
  return `/* Generated by scripts/generate-brand-environment.mts. Do not edit by hand. */
@theme static {
  --color-brand-primary: ${environment.primary};
  --color-action-primary: var(--color-brand-primary);
  --color-action-primary-hover: ${environment.actionHover};
  --color-focus-ring: ${environment.focusRing};
  --background-image-app-base: ${environment.appBackgroundImage};
  --background-image-workspace: ${environment.workspaceBackgroundImage};
  --drop-shadow-action-glow: 0 0 5px ${environment.actionGlow};
}

`;
}
