import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const root = new URL('./', import.meta.url);
const [template, styles, script] = await Promise.all([
  readFile(new URL('ui/template.html', root), 'utf8'),
  readFile(new URL('ui/styles.css', root), 'utf8'),
  build({
    entryPoints: [fileURLToPath(new URL('ui/src/app.ts', root))],
    bundle: true,
    format: 'iife',
    target: 'es2020',
    write: false,
    legalComments: 'none',
  }).then((result) => result.outputFiles[0].text),
]);

const html = template
  .replace('/*__FIGMA_UI_STYLES__*/', styles.replaceAll('</style', '<\\/style'))
  .replace('/*__FIGMA_UI_SCRIPT__*/', script.replaceAll('</script', '<\\/script'));

await mkdir(new URL('dist/', root), { recursive: true });
await writeFile(
  new URL('dist/ui.html', root),
  `<!-- Generated by build-ui.mjs; edit figma/import/ui/ instead. -->\n${html}`,
);

